### ISSUE TITLE
Invisible checkbox and ProgressBar

### ISSUE THREAD

**Issue by HectorFGarcia** [ZieIony/Carbon#191]
I've updated from 0.11.0 version to 0.12.0 and I don't why, boxes from checkboxes doesn't show up on Android 5.x and over.

![error2](https://cloud.githubusercontent.com/assets/12731574/12887106/6a2bf506-ce72-11e5-9d40-e4b72ff595ab.png)

![error3](https://cloud.githubusercontent.com/assets/12731574/12887109/6e14ac1c-ce72-11e5-8162-319f77af7f89.png)

If I downgrade back to 0.11.0, then checkboxes works fine.

**Comment by ZieIony** [comment]
Is it only the preview or is the graphics missing on a device as well? Carbon uses svg files which are not supported by the preview. It might be the reason.

**Comment by HectorFGarcia** [comment]
I've been testing on a **6.0.1** device and a **5.1.1**, same problem in both, no boxes. However, it works perfectly on a **4.0.3** device.

I tried with _android.support.v7.widget.AppCompatCheckBox_, _Checkbox_ and _carbon.widget.Checkbox_.

GPITheme is declared in styles.xml:

```
<style name="GPITheme" parent="carbon_Theme.Light.NoActionBar">
// Custom colors, nothing more.
</style>
```

If I change app theme for AppCompat (for example), checkboxes shows up. The bug only happens when I use my custom theme with that parent and Carbon 0.12.0. Carbon 0.11.0 works fine on all devices.

**Comment by ZieIony** [comment]
I just checked CheckBox and RadioButton on 2.3, 4.1, 4.3 and 5.1 and all of them worked fine. I will continue to investigate your issue. I just pushed a new commit - you can try it with jitpack, if you wish. It's the most recent version, the one I'm working with.

**Comment by HectorFGarcia** [comment]
I tried your last commit but the problem is still there. Version 0.11 works fine so I'll keep working with it. Those are de supports libs I'm using

```
compile 'com.android.support:appcompat-v7:23.2.0'
compile 'com.android.support:support-v4:23.2.0'
compile 'com.android.support:design:23.2.0'
compile 'com.android.support:recyclerview-v7:23.2.0'
```

**Comment by ZieIony** [comment]
Could you prepare a minimal, complete app, which has the issue you're experiencing? A github repo or a zip file would be fine. I've launched Carbon 0.12.0 on ~10 different phones and I wasn't able to see that.

**Comment by HectorFGarcia** [comment]
I tried again on a fresh project. Carbon checkboxes are visibles, but not native or AppCompat checkboex. Also, graphic elements as ProgressDialog's wheel are missing too. Check the added project. Sorry for the delay, I was working on another project.

![carbon](https://cloud.githubusercontent.com/assets/12731574/14073225/8a7a620e-f4c7-11e5-82b9-4d306a867ffd.png)

**Project**
[CarbonTest.zip](https://github.com/ZieIony/Carbon/files/191509/CarbonTest.zip)

**Comment by ZieIony** [comment]
If you're using Carbon theme, that would be correct. Carbon overrides styles for all widgets and these might not be compatible with AppCompat. CheckBox has its graphics set to null and the box is set from code. If you wish to use both Carbon and Android widgets, you can set styles and themes per widget.

I didn't check your code yet, but I'll do that as soon as possible.

**Comment by HectorFGarcia** [comment]
Yes, I'm using Carbon theme. I didn't know that. But, there is no style for DialogProgress?

**Comment by ZieIony** [comment]
No. I'm not sure what's going on with DialogProgress yet.

**Comment by HectorFGarcia** [comment]
The DialogProgress problem is on Android 6.0.1. I tested on 4.0.1 and the wheel shows up.

Also I found another problem on 6.0.1 that's not present on 4.01. I can tell you here or open a new issue. It's related to graphics so maybe related with this.

**Comment by ZieIony** [comment]
Cool. Open a new issue please

**Comment by ZieIony** [comment]
The ProgressBar style should extend Widget.AppCompat.ProgressBar, so it's a bug. For now you can fix it by overwriting progressBarStyle in your app, like this:

```
<style name="AppTheme" parent="carbon_Theme.Light.NoActionBar">
    <item name="android:progressBarStyle">@style/carbon_ProgressBar2</item>
</style>

<style name="carbon_ProgressBar2" parent="Widget.AppCompat.ProgressBar">
    <item name="carbon_progressStyle">bar_indeterminate</item>
    <item name="carbon_tint">?attr/colorPrimary</item>
    <item name="carbon_barWidth">3dp</item>
    <item name="carbon_inAnimation">progressWidth</item>
    <item name="carbon_outAnimation">progressWidth</item>
</style>
```

CheckBoxes are different, because their style is explicitly overriden to hide the default drawable. You can fix them by setting style to Android CheckBox style (in xml layout):

```
<CheckBox
    style="@style/Widget.AppCompat.CompoundButton.CheckBox"/>
```

Tested using your code on Android 5.1 and Android 6.0.

**Comment by ZieIony** [comment]
ProgressBar is fixed. CheckBox has to be fixed as described above due (to different paddings, drawable should be fine now).
