### ISSUE TITLE
Velocity absorbtion effect for scrollable views

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#229]

**Comment by ZieIony** [comment]
done

**Comment by Teja-Konjeti** [comment]
I'm getting NullPointerException for topGlow on absorption and no EdgeEffect when there is no background. You forgot to Initialize EdgeEffect's...

**Comment by ZieIony** [comment]
That's what happens after releasing asap :) Will fix.

**Comment by Teja-Konjeti** [comment]
Hehe..

**Comment by Teja-Konjeti** [comment]
Fixed?

**Comment by ZieIony** [comment]
Almost. Absorb should check for overscroll mode. Glows are initialized when overscroll mode is always || ifContentScrolls. That should fix NPE.

I don't know where's that background issue came from.

**Comment by Teja-Konjeti** [comment]
May be its not initialized when background is not there. U can check it with my previously uploaded sample nd remember to comment itemDecoration while testing it! :)

**Comment by ZieIony** [comment]
That was fixed before. Null background was causing draw(Canvas) to be skipped

**Comment by Teja-Konjeti** [comment]
Ohh.. wait I forgot to setOverScrollMode to always in another fragment which was default in support Library that's why it was null in my case

**Comment by Teja-Konjeti** [comment]
So there's no background Issue.. My bad, checked it!

**Comment by ZieIony** [comment]
Another push. Now it works correctly with headers and shouldn't crash.

**Comment by Teja-Konjeti** [comment]
Yep! Working!

**Comment by Teja-Konjeti** [comment]
Found another little bug, Pull EdgeEffect fully down, scroll Up the RecyclerView, EdgeEffect decelerates slower than it should be... No one would notice it just thought of informing!

**Comment by ZieIony** [comment]
Edge effects are copied from the official Android sources, so there shouldn't be any difference. I didn't notice any issues with these effects, so I'm closing this issue.
